// ═══════════════════════════════════════════════════
// LIFEBOOK - ACTIVITIES DATASET
// Edit this file to add/remove/modify activities.
// Format: { id, coach, title, advice, xp, dur, tags }
// ═══════════════════════════════════════════════════

const ACTIVITIES = [
{ id:'h1',  coach:'health', title:'Drink a glass of water',             advice:'Your body is 60% water. Start rehydrating the moment you wake up.',                        xp:5,  dur:'2 min',  tags:['morning','anytime'] },
{ id:'h2',  coach:'health', title:'Do 10 pushups',                      advice:'10 pushups a day keeps the doctor away. More than you think.',                             xp:15, dur:'3 min',  tags:['morning','afternoon'] },
{ id:'h3',  coach:'health', title:'Eat one fruit today',                advice:'A single fruit today beats planning a healthy life tomorrow.',                              xp:10, dur:'5 min',  tags:['anytime'] },
{ id:'h4',  coach:'health', title:'Take a 10-min walk outside',         advice:'Nature heals. Even a short walk clears your mind and lifts mood.',                         xp:20, dur:'10 min', tags:['afternoon','evening'] },
{ id:'h5',  coach:'health', title:'Do 5 minutes of stretching',         advice:'Flexibility prevents injury and reduces stress. Start small.',                             xp:15, dur:'5 min',  tags:['morning','evening'] },
{ id:'h6',  coach:'health', title:'Sleep before midnight',              advice:'Quality sleep is the #1 performance hack. Protect it.',                                    xp:25, dur:'—',      tags:['night'] },
{ id:'h7',  coach:'health', title:'No sugar for today',                 advice:'One clean day breaks the craving cycle. You can do this.',                                 xp:30, dur:'—',      tags:['anytime'] },
{ id:'h8',  coach:'health', title:'Eat a proper breakfast',             advice:'Breakfast fuels your brain and metabolism. Skip it and pay later.',                        xp:15, dur:'15 min', tags:['morning'] },
{ id:'h9',  coach:'health', title:'Do 20 squats',                       advice:'Squats engage your largest muscle groups and fire up energy.',                             xp:15, dur:'5 min',  tags:['morning','afternoon'] },
{ id:'h10', coach:'health', title:'Drink 2L of water today',            advice:'Track your water intake. Set small goals throughout the day.',                             xp:20, dur:'—',      tags:['anytime'] },
{ id:'h11', coach:'health', title:'Stand up and walk every hour',       advice:'Sitting too long is the new smoking. Movement resets focus.',                              xp:10, dur:'2 min',  tags:['afternoon'] },
{ id:'h12', coach:'health', title:'Do a 15-minute jog',                 advice:'Running is meditation in motion. Start slow, finish proud.',                               xp:30, dur:'15 min', tags:['morning','evening'] },
{ id:'h13', coach:'health', title:'Eat vegetables with one meal',       advice:'Just one serving of greens makes a real nutritional difference.',                          xp:10, dur:'—',      tags:['anytime'] },
{ id:'h14', coach:'health', title:'Practice deep breathing (5 min)',    advice:'5 minutes of breathwork can shift your nervous system from stress to calm.',               xp:15, dur:'5 min',  tags:['morning','night'] },
{ id:'h15', coach:'health', title:'Skip one unhealthy snack',           advice:'Willpower grows each time you say no. Every choice matters.',                             xp:10, dur:'—',      tags:['anytime'] },
{ id:'h16', coach:'health', title:'Do 30 seconds of planking',          advice:'Core strength supports everything else. Hold the plank, hold your life.',                  xp:15, dur:'1 min',  tags:['morning','afternoon'] },
{ id:'h17', coach:'health', title:'Go to bed 30 min earlier tonight',   advice:'Extra sleep tonight = sharper mind tomorrow.',                                             xp:20, dur:'—',      tags:['night'] },
{ id:'h18', coach:'health', title:'Track what you eat today',           advice:'Awareness is the first step. You can\'t improve what you don\'t measure.',                xp:15, dur:'5 min',  tags:['anytime'] },
{ id:'h19', coach:'health', title:'Do 10 jumping jacks',                advice:'Jumpstart your blood flow. Energy leads to energy.',                                       xp:10, dur:'2 min',  tags:['morning','afternoon'] },
{ id:'h20', coach:'health', title:'Take a cold shower',                 advice:'Cold showers boost alertness, immunity, and mental toughness.',                            xp:25, dur:'5 min',  tags:['morning'] },
{ id:'h21', coach:'health', title:'Walk 5000 steps today',              advice:'Step by step, your health compounds like interest.',                                        xp:25, dur:'45 min', tags:['anytime'] },
{ id:'h22', coach:'health', title:'Avoid screens 1h before sleep',      advice:'Blue light blocks melatonin. Let your brain wind down.',                                   xp:20, dur:'—',      tags:['night'] },
{ id:'h23', coach:'health', title:'Do a 7-minute HIIT workout',         advice:'Short but intense. 7 minutes can change your metabolism.',                                 xp:30, dur:'7 min',  tags:['morning','afternoon'] },
{ id:'h24', coach:'health', title:'Eat slowly and mindfully',           advice:'Slowing down helps digestion and reduces overeating.',                                     xp:10, dur:'—',      tags:['anytime'] },
{ id:'h25', coach:'health', title:'Limit caffeine after 2pm',           advice:'Late caffeine disrupts deep sleep. Protect your nights.',                                  xp:10, dur:'—',      tags:['afternoon'] },
{ id:'h26', coach:'health', title:'Do a body scan meditation',          advice:'Tune into your body. Notice tension and consciously release it.',                          xp:15, dur:'10 min', tags:['night','evening'] },
{ id:'h27', coach:'health', title:'Cook one healthy meal at home',      advice:'Homemade food = control over ingredients = control over health.',                          xp:25, dur:'30 min', tags:['afternoon','evening'] },
{ id:'h28', coach:'health', title:'Do yoga for 10 minutes',             advice:'Yoga builds strength, flexibility, and presence all at once.',                             xp:20, dur:'10 min', tags:['morning','evening'] },
{ id:'h29', coach:'health', title:'Take a multivitamin',                advice:'Fill the nutritional gaps in your diet daily.',                                            xp:5,  dur:'1 min',  tags:['morning'] },
{ id: 'h30', coach: 'health', title: 'Check your posture right now', advice: 'Sit tall, breathe deep. Good posture affects your mood and energy.', xp: 5, dur: '1 min', tags: ['anytime'] },
{ id:'h31', coach:'health', title:'Climb stairs instead of elevator', advice:'Small daily choices create lasting fitness gains.', xp:15, dur:'5 min', tags:['anytime'] },
{ id:'h32', coach:'health', title:'Eat a handful of nuts', advice:'Healthy fats and protein keep you energized longer.', xp:10, dur:'2 min', tags:['anytime'] },
{ id:'h33', coach:'health', title:'Spend 15 min in sunlight', advice:'Natural sunlight supports mood and vitamin D production.', xp:15, dur:'15 min', tags:['morning'] },
{ id:'h34', coach:'health', title:'Wash your water bottle', advice:'Clean habits protect your health in unseen ways.', xp:5, dur:'3 min', tags:['anytime'] },
{ id:'h35', coach:'health', title:'Eat without your phone', advice:'Focus on your food and enjoy mindful eating.', xp:10, dur:'20 min', tags:['anytime'] },
{ id:'h36', coach:'health', title:'Take the longer walking route', advice:'Extra movement adds up faster than you think.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'h37', coach:'health', title:'Do 15 lunges', advice:'Build leg strength and improve balance.', xp:15, dur:'5 min', tags:['morning','afternoon'] },
{ id:'h38', coach:'health', title:'Replace one soft drink with water', advice:'Your body will thank you for every healthier choice.', xp:10, dur:'1 min', tags:['anytime'] },
{ id:'h39', coach:'health', title:'Stretch your neck and shoulders', advice:'Release tension caused by screens and desk work.', xp:10, dur:'5 min', tags:['afternoon'] },
{ id:'h40', coach:'health', title:'Eat protein with one meal', advice:'Protein supports recovery and keeps you full longer.', xp:15, dur:'—', tags:['anytime'] },
{ id:'h41', coach:'health', title:'Walk after a meal', advice:'A short walk helps digestion and blood sugar control.', xp:15, dur:'10 min', tags:['afternoon','evening'] },
{ id:'h42', coach:'health', title:'Do 25 calf raises', advice:'Strong calves support balance and movement.', xp:10, dur:'3 min', tags:['anytime'] },
{ id:'h43', coach:'health', title:'Avoid fried food today', advice:'One healthier day builds momentum.', xp:20, dur:'—', tags:['anytime'] },
{ id:'h44', coach:'health', title:'Practice good sitting posture', advice:'Posture affects energy, confidence, and comfort.', xp:10, dur:'5 min', tags:['afternoon'] },
{ id:'h45', coach:'health', title:'Take a mobility break', advice:'Your joints love movement.', xp:10, dur:'5 min', tags:['afternoon'] },
{ id:'h46', coach:'health', title:'Eat a colorful meal', advice:'More colors often mean more nutrients.', xp:15, dur:'—', tags:['anytime'] },
{ id:'h47', coach:'health', title:'Do 20 bicycle crunches', advice:'Challenge your core and coordination.', xp:15, dur:'5 min', tags:['morning'] },
{ id:'h48', coach:'health', title:'Read food labels today', advice:'Awareness leads to smarter choices.', xp:10, dur:'5 min', tags:['anytime'] },
{ id:'h49', coach:'health', title:'Take 5 deep breaths before meals', advice:'Slow down and improve digestion.', xp:10, dur:'2 min', tags:['anytime'] },
{ id:'h50', coach:'health', title:'Walk barefoot on grass', advice:'Reconnect with nature and relax your mind.', xp:10, dur:'10 min', tags:['morning','evening'] },
{ id:'h51', coach:'health', title:'Do 30 mountain climbers', advice:'Boost your heart rate and energy.', xp:20, dur:'5 min', tags:['morning'] },
{ id:'h52', coach:'health', title:'Skip processed snacks today', advice:'Whole foods fuel you better.', xp:20, dur:'—', tags:['anytime'] },
{ id:'h53', coach:'health', title:'Drink water before every meal', advice:'Hydration supports appetite control.', xp:15, dur:'—', tags:['anytime'] },
{ id:'h54', coach:'health', title:'Take an eye-rest break', advice:'Look away from screens every hour.', xp:5, dur:'2 min', tags:['afternoon'] },
{ id:'h55', coach:'health', title:'Do wall sits for 1 minute', advice:'Build endurance and mental grit.', xp:15, dur:'1 min', tags:['anytime'] },
{ id:'h56', coach:'health', title:'Choose water at dinner', advice:'A simple swap with lasting benefits.', xp:10, dur:'—', tags:['evening'] },
{ id:'h57', coach:'health', title:'Do 10 burpees', advice:'Few exercises challenge the whole body like burpees.', xp:25, dur:'5 min', tags:['morning'] },
{ id:'h58', coach:'health', title:'Eat a healthy snack', advice:'Fuel your body between meals wisely.', xp:10, dur:'5 min', tags:['afternoon'] },
{ id:'h59', coach:'health', title:'Take a stretch break during work', advice:'Your productivity improves when your body moves.', xp:10, dur:'5 min', tags:['afternoon'] },
{ id:'h60', coach:'health', title:'Avoid eating while watching TV', advice:'Mindful eating helps prevent overeating.', xp:10, dur:'—', tags:['evening'] },
{ id:'h61', coach:'health', title:'Do 50 jumping ropes', advice:'Quick cardio can refresh your whole day.', xp:20, dur:'5 min', tags:['morning'] },
{ id:'h62', coach:'health', title:'Replace one sugary snack with fruit', advice:'Healthier choices compound over time.', xp:15, dur:'5 min', tags:['anytime'] },
{ id:'h63', coach:'health', title:'Practice balance on one leg', advice:'Balance training improves stability and coordination.', xp:10, dur:'3 min', tags:['anytime'] },
{ id:'h64', coach:'health', title:'Walk during a phone call', advice:'Turn idle time into active time.', xp:10, dur:'10 min', tags:['afternoon'] },
{ id:'h65', coach:'health', title:'Do 15 tricep dips', advice:'Strengthen your arms using body weight.', xp:15, dur:'5 min', tags:['morning'] },
{ id:'h66', coach:'health', title:'Add greens to your meal', advice:'Small nutrition upgrades matter.', xp:10, dur:'—', tags:['anytime'] },
{ id:'h67', coach:'health', title:'Take 1000 extra steps today', advice:'Extra steps create extra health.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'h68', coach:'health', title:'Spend 10 minutes standing', advice:'Break long sitting sessions regularly.', xp:5, dur:'10 min', tags:['afternoon'] },
{ id:'h69', coach:'health', title:'Do 20 high knees', advice:'Wake up your body instantly.', xp:10, dur:'3 min', tags:['morning'] },
{ id:'h70', coach:'health', title:'Eat dinner before 9pm', advice:'Earlier meals often support better sleep.', xp:15, dur:'—', tags:['evening'] },
{ id:'h71', coach:'health', title:'Try a healthy recipe', advice:'Learning healthy cooking is a lifelong investment.', xp:25, dur:'30 min', tags:['evening'] },
{ id:'h72', coach:'health', title:'Foam roll or self-massage', advice:'Recovery is part of fitness.', xp:15, dur:'10 min', tags:['night'] },
{ id:'h73', coach:'health', title:'Do 3 minutes of shadow boxing', advice:'Fun movement is still movement.', xp:15, dur:'3 min', tags:['morning'] },
{ id:'h74', coach:'health', title:'Check your hydration level', advice:'Your energy often reflects your hydration.', xp:5, dur:'2 min', tags:['anytime'] },
{ id:'h75', coach:'health', title:'Walk while listening to a podcast', advice:'Learn and move at the same time.', xp:15, dur:'20 min', tags:['afternoon'] },
{ id:'h76', coach:'health', title:'Do 40 seconds of planking', advice:'A stronger core supports every movement.', xp:20, dur:'1 min', tags:['morning'] },
{ id:'h77', coach:'health', title:'Eat until 80% full', advice:'Leave room before you feel stuffed.', xp:15, dur:'—', tags:['anytime'] },
{ id:'h78', coach:'health', title:'Take the stairs for the whole day', advice:'Turn everyday movement into exercise.', xp:20, dur:'—', tags:['anytime'] },
{ id:'h79', coach:'health', title:'Do a full-body stretch before bed', advice:'End the day relaxed and recovered.', xp:15, dur:'10 min', tags:['night'] },
{ id:'h80', coach:'health', title:'Complete a workout of your choice', advice:'The best workout is the one you actually do.', xp:30, dur:'20 min', tags:['anytime'] },

{ id:'d1',  coach:'deen', title:'Recite Al-Fatiha with reflection',    advice:'Al-Fatiha is a conversation with Allah. Slow down and mean every word.',                   xp:15, dur:'3 min',  tags:['morning','anytime'] },
{ id:'d2',  coach:'deen', title:'Read 1 page of Quran',                advice:'One page a day — consistent, sustainable, blessed.',                                       xp:20, dur:'5 min',  tags:['morning','evening'] },
{ id:'d3',  coach:'deen', title:'Pray Fajr on time',                   advice:'The one who catches Fajr is protected all day. Start right.',                              xp:30, dur:'10 min', tags:['morning'] },
{ id:'d4',  coach:'deen', title:'Make 10 minutes of dhikr',            advice:'Remembrance of Allah brings peace the world cannot give.',                                 xp:20, dur:'10 min', tags:['anytime'] },
{ id:'d5',  coach:'deen', title:'Say Bismillah before every task',     advice:'Begin everything with Allah\'s name and watch your barakah multiply.',                     xp:5,  dur:'—',      tags:['anytime'] },
{ id:'d6',  coach:'deen', title:'Listen to one Islamic lecture',       advice:'10 minutes of Islamic knowledge daily transforms your perspective.',                       xp:20, dur:'10 min', tags:['afternoon','evening'] },
{ id:'d7',  coach:'deen', title:'Give something in charity today',     advice:'Sadaqah does not decrease wealth. It purifies and multiplies.',                            xp:25, dur:'5 min',  tags:['anytime'] },
{ id:'d8',  coach:'deen', title:'Memorize one new dua',                advice:'Every dua memorized is a gift you carry with you forever.',                                xp:20, dur:'10 min', tags:['evening','night'] },
{ id:'d9',  coach:'deen', title:'Perform Ishraq prayer',               advice:'2 rakat after sunrise brings rewards of Hajj and Umrah.',                                  xp:25, dur:'5 min',  tags:['morning'] },
{ id:'d10', coach:'deen', title:'Recite Ayat ul Kursi after prayer',   advice:'Protection and peace come with this powerful verse.',                                      xp:10, dur:'2 min',  tags:['anytime'] },
{ id:'d11', coach:'deen', title:'Make Istighfar 100 times',            advice:'The Prophet ﷺ sought forgiveness 100 times daily. Follow his Sunnah.',                   xp:20, dur:'5 min',  tags:['morning','night'] },
{ id:'d12', coach:'deen', title:'Pray Tahajjud tonight',               advice:'The last third of night: the best time to whisper your needs to Allah.',                  xp:40, dur:'15 min', tags:['night'] },
{ id:'d13', coach:'deen', title:'Read about a Prophet\'s story',       advice:'Their patience and trust in Allah will strengthen yours.',                                 xp:20, dur:'15 min', tags:['evening'] },
{ id:'d14', coach:'deen', title:'Fast a Sunnah fast this week',        advice:'Fasting Monday or Thursday is Sunnah. Reserve one this week.',                            xp:50, dur:'—',      tags:['morning'] },
{ id:'d15', coach:'deen', title:'Send salawat on the Prophet ﷺ 10x',   advice:'Every salawat brings 10 blessings from Allah. It costs nothing.',                         xp:10, dur:'2 min',  tags:['anytime'] },
{ id:'d16', coach:'deen', title:'Make dua for your parents',           advice:'A prayer for your parents is one of the greatest gifts you can give.',                     xp:15, dur:'5 min',  tags:['anytime'] },
{ id:'d17', coach:'deen', title:'Recite the 3 Quls before sleep',      advice:'Al-Ikhlas, Al-Falaq, An-Nas — protection before the night.',                              xp:10, dur:'3 min',  tags:['night'] },
{ id:'d18', coach:'deen', title:'Avoid one haram thing intentionally', advice:'Every conscious choice for halal strengthens your taqwa.',                                 xp:30, dur:'—',      tags:['anytime'] },
{ id:'d19', coach:'deen', title:'Make wudu and stay in a state of it', advice:'Wudu is armor. Maintaining it keeps you connected to worship.',                            xp:15, dur:'5 min',  tags:['morning','anytime'] },
{ id:'d20', coach:'deen', title:'Reflect on a verse of Quran deeply', advice:'One verse deeply understood changes more than 100 pages read quickly.', xp:25, dur:'10 min', tags:['evening','night'] },

{ id:'l1',  coach:'learning', title:'Read 10 pages of a book',           advice:'Ten pages daily = 12 books a year. That\'s how legends grow.',                          xp:20, dur:'20 min', tags:['morning','evening','office'] },
{ id:'l2',  coach:'learning', title:'Watch one educational video',       advice:'YouTube is a university. Use it like one.',                                               xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l3',  coach:'learning', title:'Learn 5 new vocabulary words',      advice:'Language is power. Expanding it expands your thinking.',                                 xp:15, dur:'10 min', tags:['morning','office'] },
{ id:'l4',  coach:'learning', title:'Practice SQL for 20 minutes',       advice:'Data literacy is the skill of the decade. Start today.',                                 xp:25, dur:'20 min', tags:['office','afternoon'] },
{ id:'l5',  coach:'learning', title:'Study Laravel for 30 minutes',      advice:'Mastery is the accumulation of daily sessions. No shortcuts.',                           xp:30, dur:'30 min', tags:['office','afternoon'] },
{ id:'l6',  coach:'learning', title:'Practice Python basics',            advice:'Python is the most versatile language in the world. Learn it.',                          xp:25, dur:'25 min', tags:['office','afternoon'] },
{ id:'l7',  coach:'learning', title:'Listen to an educational podcast',  advice:'30 minutes of podcast = 30 minutes of mentorship from the best.',                       xp:20, dur:'30 min', tags:['anytime'] },
{ id:'l8',  coach:'learning', title:'Take notes on what you learned',    advice:'Writing forces clarity. Your notes are your second brain.',                              xp:10, dur:'10 min', tags:['evening','night'] },
{ id:'l9',  coach:'learning', title:'Study Redis concepts for 20 min',   advice:'Caching knowledge is as valuable as caching data.',                                     xp:25, dur:'20 min', tags:['office'] },
{ id:'l10', coach:'learning', title:'Watch a TED Talk',                  advice:'18 minutes with the right idea can change your entire worldview.',                       xp:20, dur:'18 min', tags:['evening','anytime'] },
{ id:'l11', coach:'learning', title:'Solve one coding challenge',        advice:'Each problem you solve makes the next one easier.',                                      xp:30, dur:'30 min', tags:['office','afternoon'] },
{ id:'l12', coach:'learning', title:'Study a design pattern',            advice:'Patterns are the shortcut to writing code that scales.',                                 xp:25, dur:'20 min', tags:['office'] },
{ id:'l13', coach:'learning', title:'Learn about system design',         advice:'System design is what separates juniors from seniors.',                                  xp:30, dur:'30 min', tags:['office','afternoon'] },
{ id:'l14', coach:'learning', title:'Practice typing speed',             advice:'Faster typing means more time coding, not typing.',                                      xp:10, dur:'10 min', tags:['anytime'] },
{ id:'l15', coach:'learning', title:'Review your notes from this week',  advice:'Spaced repetition is how knowledge sticks. Review regularly.',                          xp:15, dur:'15 min', tags:['evening','night'] },
{ id:'l16', coach:'learning', title:'Learn about REST API design',       advice:'APIs are the language software speaks. Know it well.',                                  xp:25, dur:'20 min', tags:['office'] },
{ id:'l17', coach:'learning', title:'Study CSS Grid/Flexbox',            advice:'Layout mastery unlocks beautiful UIs.',                                                  xp:20, dur:'20 min', tags:['office','afternoon'] },
{ id:'l18', coach:'learning', title:'Read a tech blog or article',       advice:'Staying current is part of the job. Read 15 min daily.',                                xp:10, dur:'15 min', tags:['morning','office'] },
{ id:'l19', coach:'learning', title:'Build a small side project',        advice:'Building is the fastest way to learn. Code it to understand it.',                       xp:40, dur:'1 hour', tags:['afternoon','evening'] },
{ id:'l20', coach:'learning', title:'Learn Git best practices', advice:'Version control is not optional. Master it early.', xp:20, dur:'20 min', tags:['office'] },
{ id:'l21', coach:'learning', title:'Read one chapter of a book', advice:'A chapter a day compounds into expertise over time.', xp:20, dur:'20 min', tags:['morning','evening'] },
{ id:'l22', coach:'learning', title:'Learn one new English phrase', advice:'Fluency is built phrase by phrase.', xp:10, dur:'5 min', tags:['anytime'] },
{ id:'l23', coach:'learning', title:'Watch a documentary', advice:'Great documentaries compress years of learning into hours.', xp:25, dur:'45 min', tags:['evening'] },
{ id:'l24', coach:'learning', title:'Read about world history', advice:'History explains the present better than headlines do.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'l25', coach:'learning', title:'Learn a geography fact', advice:'Knowing the world makes you a better thinker.', xp:10, dur:'5 min', tags:['anytime'] },
{ id:'l26', coach:'learning', title:'Study a famous person\'s biography', advice:'Success leaves clues. Learn from those who came before.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'l27', coach:'learning', title:'Write down 3 things you learned today', advice:'Reflection turns information into wisdom.', xp:15, dur:'10 min', tags:['night'] },
{ id:'l28', coach:'learning', title:'Learn a public speaking tip', advice:'Communication multiplies every other skill.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l29', coach:'learning', title:'Read a news article deeply', advice:'Go beyond headlines and understand the full story.', xp:10, dur:'15 min', tags:['morning'] },
{ id:'l30', coach:'learning', title:'Learn a negotiation principle', advice:'Negotiation is a life skill, not just a business skill.', xp:20, dur:'15 min', tags:['anytime'] },
{ id:'l31', coach:'learning', title:'Memorize a meaningful quote', advice:'Great ideas are worth carrying with you.', xp:10, dur:'5 min', tags:['anytime'] },
{ id:'l32', coach:'learning', title:'Learn one psychology concept', advice:'Understanding people starts with understanding the mind.', xp:20, dur:'15 min', tags:['evening'] },
{ id:'l33', coach:'learning', title:'Study body language basics', advice:'Most communication happens without words.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l34', coach:'learning', title:'Learn a memory technique', advice:'A trained memory is a superpower.', xp:20, dur:'15 min', tags:['anytime'] },
{ id:'l35', coach:'learning', title:'Practice active listening', advice:'Listen to understand, not to reply.', xp:15, dur:'10 min', tags:['social'] },
{ id:'l36', coach:'learning', title:'Learn a financial term', advice:'Financial literacy creates freedom.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l37', coach:'learning', title:'Read about investing basics', advice:'Investing rewards patience and knowledge.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'l38', coach:'learning', title:'Learn about a new country', advice:'Curiosity expands your worldview.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l39', coach:'learning', title:'Read a science article', advice:'Science teaches you how the world really works.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l40', coach:'learning', title:'Learn a productivity principle', advice:'Working smarter is a learnable skill.', xp:15, dur:'10 min', tags:['office'] },
{ id:'l41', coach:'learning', title:'Practice mental math', advice:'A sharper mind comes from regular exercise too.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l42', coach:'learning', title:'Learn a new word in another language', advice:'Every language opens a new way of thinking.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l43', coach:'learning', title:'Research a topic you are curious about', advice:'Curiosity is the engine of lifelong learning.', xp:20, dur:'20 min', tags:['anytime'] },
{ id:'l44', coach:'learning', title:'Read a book summary', advice:'A summary can spark deeper exploration.', xp:10, dur:'10 min', tags:['evening'] },
{ id:'l45', coach:'learning', title:'Learn a critical thinking concept', advice:'Think clearly before thinking quickly.', xp:20, dur:'15 min', tags:['anytime'] },
{ id:'l46', coach:'learning', title:'Watch an educational interview', advice:'Learn directly from experienced minds.', xp:20, dur:'30 min', tags:['evening'] },
{ id:'l47', coach:'learning', title:'Learn about nutrition', advice:'Your body follows the quality of your fuel.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l48', coach:'learning', title:'Study a famous invention', advice:'Innovation begins with curiosity.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l49', coach:'learning', title:'Learn one leadership lesson', advice:'Leadership starts with leading yourself.', xp:20, dur:'15 min', tags:['office'] },
{ id:'l50', coach:'learning', title:'Reflect on a past mistake', advice:'Lessons learned become future advantages.', xp:15, dur:'10 min', tags:['night'] },
{ id:'l51', coach:'learning', title:'Learn about emotional intelligence', advice:'Success depends on EQ as much as IQ.', xp:20, dur:'15 min', tags:['social'] },
{ id:'l52', coach:'learning', title:'Read about personal finance', advice:'Every dollar you understand works harder for you.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'l53', coach:'learning', title:'Learn a persuasion technique', advice:'Influence comes from understanding people.', xp:15, dur:'10 min', tags:['social'] },
{ id:'l54', coach:'learning', title:'Study a cultural tradition', advice:'Different cultures teach different wisdom.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l55', coach:'learning', title:'Practice storytelling', advice:'Stories move people more than facts alone.', xp:20, dur:'15 min', tags:['social'] },
{ id:'l56', coach:'learning', title:'Learn one business lesson', advice:'Business is ultimately about solving problems.', xp:20, dur:'15 min', tags:['office'] },
{ id:'l57', coach:'learning', title:'Read a philosophy quote and reflect', advice:'Philosophy teaches how to think, not what to think.', xp:15, dur:'10 min', tags:['night'] },
{ id:'l58', coach:'learning', title:'Learn a decision-making framework', advice:'Better decisions create a better life.', xp:20, dur:'15 min', tags:['office'] },
{ id:'l59', coach:'learning', title:'Study a successful habit', advice:'Your habits shape your future.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l60', coach:'learning', title:'Learn about human behavior', advice:'People are the most important subject to understand.', xp:20, dur:'15 min', tags:['social'] },
{ id:'l61', coach:'learning', title:'Read about climate and environment', advice:'Understanding the planet helps protect it.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'l62', coach:'learning', title:'Analyze a successful person', advice:'Success patterns can be studied and adapted.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'l63', coach:'learning', title:'Learn one sales principle', advice:'Everyone sells ideas, whether they realize it or not.', xp:15, dur:'10 min', tags:['office'] },
{ id:'l64', coach:'learning', title:'Read a research-backed article', advice:'Facts are stronger when supported by evidence.', xp:20, dur:'20 min', tags:['anytime'] },
{ id:'l65', coach:'learning', title:'Practice observation skills', advice:'Most people look. Few people truly observe.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l66', coach:'learning', title:'Learn about a famous historical event', advice:'History repeats for those who ignore it.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'l67', coach:'learning', title:'Watch a university lecture', advice:'World-class education is often free online.', xp:25, dur:'30 min', tags:['evening'] },
{ id:'l68', coach:'learning', title:'Read a chapter on self-development', advice:'Investing in yourself has the highest return.', xp:20, dur:'20 min', tags:['morning'] },
{ id:'l69', coach:'learning', title:'Learn a creativity technique', advice:'Creativity is a skill, not a gift.', xp:15, dur:'10 min', tags:['anytime'] },
{ id:'l70', coach:'learning', title:'Teach someone what you learned', advice:'If you can teach it, you understand it.', xp:25, dur:'15 min', tags:['social'] },
{ id:'l71', coach:'learning', title:'Write a lesson from today', advice:'Capture lessons before they disappear.', xp:10, dur:'5 min', tags:['night'] },
{ id:'l72', coach:'learning', title:'Learn about time management', advice:'Time is your most valuable asset.', xp:15, dur:'10 min', tags:['office'] },
{ id:'l73', coach:'learning', title:'Read about healthy relationships', advice:'Relationships shape happiness more than achievement.', xp:20, dur:'15 min', tags:['social'] },
{ id:'l74', coach:'learning', title:'Learn one negotiation tactic', advice:'Small improvements create stronger outcomes.', xp:15, dur:'10 min', tags:['social'] },
{ id:'l75', coach:'learning', title:'Study a famous speech', advice:'Great speakers leave behind great lessons.', xp:20, dur:'15 min', tags:['evening'] },
{ id:'l76', coach:'learning', title:'Learn about habits and behavior change', advice:'Change becomes easier when you understand it.', xp:20, dur:'15 min', tags:['anytime'] },
{ id:'l77', coach:'learning', title:'Read about mindfulness', advice:'Attention is your most powerful resource.', xp:15, dur:'10 min', tags:['morning'] },
{ id:'l78', coach:'learning', title:'Explore a topic outside your field', advice:'Innovation often happens at the intersection of disciplines.', xp:20, dur:'20 min', tags:['anytime'] },
{ id:'l79', coach:'learning', title:'Review your personal goals', advice:'Learning is meaningful when it serves a direction.', xp:15, dur:'10 min', tags:['night'] },
{ id:'l80', coach:'learning', title:'Journal a new idea', advice:'Big ideas often start as small notes.', xp:15, dur:'5 min', tags:['night'] },

{ id:'c1',  coach:'career', title:'Update your LinkedIn profile',       advice:'Your profile is your 24/7 salesperson. Keep it sharp.',                                   xp:20, dur:'20 min', tags:['office','afternoon'] },
{ id:'c2',  coach:'career', title:'Send one professional email',        advice:'One well-written email can open a door you didn\'t know existed.',                        xp:10, dur:'10 min', tags:['office','morning'] },
{ id:'c3',  coach:'career', title:'Reach out to one industry contact',  advice:'Your network is your net worth. Invest 10 minutes in it today.',                          xp:20, dur:'10 min', tags:['office','afternoon'] },
{ id:'c4',  coach:'career', title:'Work on your CV/portfolio',          advice:'Opportunities are taken by those who were ready before they came.',                        xp:25, dur:'30 min', tags:['evening','afternoon'] },
{ id:'c5',  coach:'career', title:'Set 3 goals for this week',          advice:'Without a target, every direction is wrong. Define yours.',                               xp:15, dur:'10 min', tags:['morning','office'] },
{ id:'c6',  coach:'career', title:'Study a skill in your field',        advice:'Those who stop learning stop growing. Invest an hour.',                                   xp:30, dur:'30 min', tags:['office','afternoon'] },
{ id:'c7',  coach:'career', title:'Ask for feedback from a colleague',  advice:'Feedback is a gift. The brave ask for it.',                                               xp:15, dur:'10 min', tags:['office'] },
{ id:'c8',  coach:'career', title:'Review your long-term career goals', advice:'Clarity of direction creates energy of action.',                                          xp:20, dur:'15 min', tags:['evening','night'] },
{ id:'c9',  coach:'career', title:'Learn about your industry trends',   advice:'The professional who understands trends beats the one who just executes.',                xp:20, dur:'20 min', tags:['office','afternoon'] },
{ id:'c10', coach:'career', title:'Practice public speaking for 5 min', advice:'Communication is the highest-paid skill. Practice it.',                                  xp:20, dur:'5 min',  tags:['anytime'] },
{ id:'c11', coach:'career', title:'Prepare for a potential interview',  advice:'Practice questions even when you\'re not job hunting. Stay sharp.',                      xp:25, dur:'20 min', tags:['evening'] },
{ id:'c12', coach:'career', title:'Complete one task fully before next',advice:'Deep work on one thing beats shallow work on ten.',                                       xp:15, dur:'—',      tags:['office'] },
{ id:'c13', coach:'career', title:'Learn about leadership principles',  advice:'Leadership is not a title. It\'s a daily choice.',                                        xp:20, dur:'15 min', tags:['evening','office'] },
{ id:'c14', coach:'career', title:'Build a new work habit today',       advice:'Small consistent habits build extraordinary careers.',                                    xp:15, dur:'—',      tags:['morning','office'] },
{ id: 'c15', coach: 'career', title: 'Document something you built', advice: 'Documenting your work shows mastery and builds portfolio.', xp: 20, dur: '20 min', tags: ['office', 'afternoon'] },
{ id:'c16', coach:'career', title:'Write a work accomplishment', advice:'If you do not track wins, you will forget them when opportunity arrives.', xp:15, dur:'10 min', tags:['office'] },
{ id:'c17', coach:'career', title:'Share a professional insight', advice:'Visibility creates opportunities. Let people know what you know.', xp:20, dur:'10 min', tags:['office','social'] },
{ id:'c18', coach:'career', title:'Learn one business concept', advice:'The higher you go, the less you are paid for tasks and the more for decisions.', xp:20, dur:'15 min', tags:['office'] },
{ id:'c19', coach:'career', title:'Identify one process improvement', advice:'Top performers don\'t just do work. They improve how work gets done.', xp:25, dur:'15 min', tags:['office'] },
{ id:'c20', coach:'career', title:'Teach a colleague something', advice:'Teaching builds authority and deepens your understanding.', xp:25, dur:'20 min', tags:['office'] },
{ id:'c21', coach:'career', title:'Write a career journal entry', advice:'Reflection turns experience into wisdom.', xp:15, dur:'10 min', tags:['night'] },
{ id:'c22', coach:'career', title:'Study a successful professional', advice:'Success leaves clues if you pay attention.', xp:20, dur:'20 min', tags:['evening'] },
{ id:'c23', coach:'career', title:'Ask one thoughtful question in a meeting', advice:'Curiosity often creates more value than talking.', xp:15, dur:'5 min', tags:['office'] },
{ id:'c24', coach:'career', title:'Review your salary market value', advice:'Know your market worth before you need it.', xp:25, dur:'20 min', tags:['evening'] },
{ id:'c25', coach:'career', title:'Practice negotiation skills', advice:'Every career eventually rewards those who can negotiate.', xp:20, dur:'15 min', tags:['office'] },
{ id:'c26', coach:'career', title:'Build a personal brand asset', advice:'A portfolio, article, or project works while you sleep.', xp:30, dur:'30 min', tags:['evening'] },
{ id:'c27', coach:'career', title:'Write a LinkedIn post', advice:'People cannot recognize your expertise if they never see it.', xp:25, dur:'20 min', tags:['social'] },
{ id:'c28', coach:'career', title:'Read a leadership article', advice:'Leadership is learned long before the title arrives.', xp:15, dur:'15 min', tags:['office'] },
{ id:'c29', coach:'career', title:'Improve one workplace relationship', advice:'Careers grow faster through collaboration than competition.', xp:20, dur:'10 min', tags:['social'] },
{ id:'c30', coach:'career', title:'Learn one stakeholder management lesson', advice:'Managing expectations is often harder than managing work.', xp:20, dur:'15 min', tags:['office'] },
{ id:'c31', coach:'career', title:'Document a career lesson', advice:'Capture lessons while they are fresh and valuable.', xp:15, dur:'10 min', tags:['night'] },
{ id:'c32', coach:'career', title:'Review your professional goals', advice:'What gets reviewed gets improved.', xp:15, dur:'10 min', tags:['night'] },
{ id:'c33', coach:'career', title:'Learn one decision-making framework', advice:'Better decisions create better careers.', xp:20, dur:'15 min', tags:['office'] },
{ id:'c34', coach:'career', title:'Create a learning roadmap', advice:'Growth is easier when you know the next step.', xp:20, dur:'20 min', tags:['office'] },
{ id:'c35', coach:'career', title:'Volunteer for a responsibility', advice:'Ownership is often noticed before skill.', xp:30, dur:'—', tags:['office'] },
{ id:'c36', coach:'career', title:'Prepare a meeting agenda', advice:'People who create clarity become leaders naturally.', xp:20, dur:'10 min', tags:['office'] },
{ id:'c37', coach:'career', title:'Review your weekly progress', advice:'High performers measure themselves regularly.', xp:15, dur:'10 min', tags:['weekly'] },
{ id:'c38', coach:'career', title:'Practice explaining a complex topic', advice:'If you can simplify it, you truly understand it.', xp:20, dur:'15 min', tags:['office'] },
{ id:'c39', coach:'career', title:'Help solve a team problem', advice:'Impact matters more than job descriptions.', xp:30, dur:'30 min', tags:['office'] },
{ id:'c40', coach:'career', title:'Build a case study from your work', advice:'Your experience becomes valuable when it is documented.', xp:30, dur:'30 min', tags:['evening'] },

{ id:'f1',  coach:'family', title:'Call a parent or sibling',           advice:'One call means more than a thousand messages.',                                            xp:20, dur:'10 min', tags:['evening','afternoon'] },
{ id:'f2',  coach:'family', title:'Have dinner with family',            advice:'The table is where families are built. Show up for it.',                                  xp:20, dur:'30 min', tags:['evening'] },
{ id:'f3',  coach:'family', title:'Express gratitude to a family member',advice:'Say it today. Do not assume they know.',                                                 xp:15, dur:'5 min',  tags:['anytime','evening'] },
{ id:'f4',  coach:'family', title:'Help with one household task',       advice:'Service to family is worship. Do it with love.',                                          xp:15, dur:'15 min', tags:['evening','morning'] },
{ id:'f5',  coach:'family', title:'Play with your kids or siblings',    advice:'They won\'t be this age again. Be present while you can.',                                xp:25, dur:'20 min', tags:['evening','afternoon'] },
{ id:'f6',  coach:'family', title:'Check in on an elderly relative',    advice:'A moment of your time is a lifetime of comfort for them.',                                xp:20, dur:'10 min', tags:['anytime'] },
{ id:'f7',  coach:'family', title:'Write a letter or message to family',advice:'Words of love, written down, last forever.',                                              xp:20, dur:'15 min', tags:['evening','night'] },
{ id:'f8',  coach:'family', title:'Plan a family outing this weekend',  advice:'Shared memories are the greatest inheritance you can give.',                              xp:20, dur:'10 min', tags:['afternoon','evening'] },
{ id:'f9',  coach:'family', title:'Apologize if you owe one',           advice:'Humility in relationships builds unbreakable bonds.',                                     xp:25, dur:'10 min', tags:['anytime'] },
{ id:'f10', coach:'family', title:'Make a meal for family',             advice:'Food is love in action. Cook something with intention today.',                            xp:25, dur:'30 min', tags:['evening'] },
{ id:'f11',  coach:'family', title:'Call your Sasuma',           advice:'One call means more than a thousand messages.',                                            xp:20, dur:'10 min', tags:['evening','afternoon'] },
{ id:'f12',  coach:'family', title:'Call your Shali',           advice:'One call means more than a thousand messages.',                                            xp:20, dur:'10 min', tags:['evening','afternoon'] },
{ id:'f13',  coach:'family', title:'Call a Friend',           advice:'One call means more than a thousand messages.',                                            xp:20, dur:'10 min', tags:['evening','afternoon'] },
{ id:'f14',  coach:'family', title:'Call your Shala',           advice:'One call means more than a thousand messages.',                                            xp:20, dur:'10 min', tags:['evening','afternoon'] },
{ id:'f15',  coach:'family', title:'Call a relative',           advice:'One call means more than a thousand messages.',                                            xp:20, dur:'10 min', tags:['evening','afternoon'] },

{ id:'m1',  coach:'money', title:'Track every expense today',           advice:'Money untracked is money lost. Awareness is the first step.',                             xp:15, dur:'5 min',  tags:['anytime','evening'] },
{ id:'m2',  coach:'money', title:'Review your monthly budget',          advice:'A budget is a plan for your money to do something useful.',                               xp:20, dur:'15 min', tags:['evening','office'] },
{ id:'m3',  coach:'money', title:'Save 1% of today\'s income',         advice:'Start absurdly small. The habit matters more than the amount.',                           xp:25, dur:'5 min',  tags:['anytime'] },
{ id:'m4',  coach:'money', title:'Learn about investing basics',        advice:'Investing knowledge is the one skill that pays you forever.',                             xp:25, dur:'20 min', tags:['evening','office'] },
{ id:'m5',  coach:'money', title:'Cut one unnecessary subscription',    advice:'Small leaks sink great ships. Audit your subscriptions.',                                 xp:20, dur:'10 min', tags:['anytime'] },
{ id:'m6',  coach:'money', title:'Research a financial goal',           advice:'Know the number you\'re working toward. Goals without numbers are wishes.',               xp:15, dur:'10 min', tags:['evening'] },
{ id:'m7',  coach:'money', title:'Calculate your net worth',            advice:'What you own minus what you owe. Know this number.',                                      xp:20, dur:'15 min', tags:['evening','office'] },
{ id:'m8',  coach:'money', title:'Read about personal finance',         advice:'Every chapter of a finance book is worth more than the cover price.',                    xp:20, dur:'20 min', tags:['evening','office'] },
{ id:'m9',  coach:'money', title:'Avoid one unnecessary purchase',      advice:'Delayed gratification is how wealth is built.',                                           xp:10, dur:'—',      tags:['anytime'] },
{ id:'m10', coach: 'money', title: 'Set a savings goal for this month', advice: 'Define the destination before the journey.', xp: 20, dur: '10 min', tags: ['morning', 'evening'] },

{ id:'mn1', coach:'mental', title:'Write in a journal for 5 minutes',  advice:'Journaling converts chaos in your mind to clarity on paper.',                              xp:20, dur:'5 min',  tags:['night','evening'] },
{ id:'mn2', coach:'mental', title:'Practice gratitude — list 3 things',advice:'Gratitude is not a feeling. It\'s a practice. Start now.',                                xp:15, dur:'3 min',  tags:['morning','night'] },
{ id:'mn3', coach:'mental', title:'Do nothing for 5 minutes',          advice:'Rest is not laziness. It\'s maintenance for a high-performing mind.',                     xp:10, dur:'5 min',  tags:['anytime'] },
{ id:'mn4', coach:'mental', title:'Speak kindly to yourself today',    advice:'You are your longest relationship. Speak accordingly.',                                    xp:15, dur:'—',      tags:['anytime'] },
{ id:'mn5', coach:'mental', title:'Meditate for 5 minutes',            advice:'Meditation is weight training for your attention. Show up.',                               xp:20, dur:'5 min',  tags:['morning','evening','night'] },
{ id:'mn6', coach:'mental', title:'Identify and name your emotion',    advice:'Naming an emotion reduces its power. Say it to own it.',                                  xp:10, dur:'2 min',  tags:['anytime'] },
{ id:'mn7', coach:'mental', title:'Read a few pages of fiction',       advice:'Fiction builds empathy and gives your analytical mind a rest.',                            xp:15, dur:'15 min', tags:['evening','night'] },
{ id:'mn8', coach:'mental', title:'Write down your worries',           advice:'Worries trapped in your head grow. On paper, you see them shrink.',                       xp:15, dur:'5 min',  tags:['night','evening'] },
{ id:'mn9', coach:'mental', title:'Go outside and observe nature',     advice:'Nature restores the depleted mind. Just 5 minutes helps.',                                xp:15, dur:'10 min', tags:['morning','afternoon','evening'] },
{ id:'mn10', coach: 'mental', title: 'Talk to someone you trust', advice: 'Connection heals. Reach out. You don\'t have to carry this alone.', xp: 20, dur: '—', tags: ['anytime', 'evening'] },
{ id:'mn11', coach:'mental', title:'Take 10 slow deep breaths', advice:'A calm breath is a signal to your brain that you are safe.', xp:10, dur:'2 min', tags:['anytime'] },
{ id:'mn12', coach:'mental', title:'Notice one negative thought', advice:'You are not your thoughts. You are the observer of them.', xp:15, dur:'5 min', tags:['anytime'] },
{ id:'mn13', coach:'mental', title:'Challenge a limiting belief', advice:'Growth begins when old assumptions are questioned.', xp:20, dur:'10 min', tags:['evening'] },
{ id:'mn14', coach:'mental', title:'Write one thing you are proud of', advice:'Confidence grows when progress is acknowledged.', xp:15, dur:'5 min', tags:['night'] },
{ id:'mn15', coach:'mental', title:'Forgive yourself for one mistake', advice:'Self-compassion creates more growth than self-criticism.', xp:20, dur:'10 min', tags:['night'] },
{ id:'mn16', coach:'mental', title:'Take a break from notifications', advice:'Attention is your most valuable mental resource.', xp:20, dur:'30 min', tags:['afternoon'] },
{ id:'mn17', coach:'mental', title:'Sit quietly without distractions', advice:'Silence reveals what noise often hides.', xp:15, dur:'10 min', tags:['morning','evening'] },
{ id:'mn18', coach:'mental', title:'Identify one stress trigger', advice:'Awareness is the first step toward control.', xp:15, dur:'5 min', tags:['anytime'] },
{ id:'mn19', coach:'mental', title:'Write a positive affirmation', advice:'The words you repeat become the beliefs you carry.', xp:10, dur:'3 min', tags:['morning'] },
{ id:'mn20', coach:'mental', title:'Practice mindful eating', advice:'Slow down. Presence turns routine into peace.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'mn21', coach:'mental', title:'Declutter one small space', advice:'An organized environment supports an organized mind.', xp:15, dur:'10 min', tags:['afternoon'] },
{ id:'mn22', coach:'mental', title:'Reflect on today’s biggest lesson', advice:'Experience becomes wisdom only through reflection.', xp:20, dur:'10 min', tags:['night'] },
{ id:'mn23', coach:'mental', title:'Take a social media break', advice:'Protect your peace as carefully as your productivity.', xp:20, dur:'1 hour', tags:['anytime'] },
{ id:'mn24', coach:'mental', title:'Practice active listening', advice:'Being fully present is one of the greatest gifts you can give.', xp:20, dur:'10 min', tags:['social'] },
{ id:'mn25', coach:'mental', title:'Write a letter to your future self', advice:'Future clarity begins with present intention.', xp:25, dur:'15 min', tags:['night'] },
{ id:'mn26', coach:'mental', title:'Accept something you cannot control', advice:'Peace often begins where resistance ends.', xp:20, dur:'5 min', tags:['anytime'] },
{ id:'mn27', coach:'mental', title:'List 3 recent wins', advice:'Progress feels better when it is recognized.', xp:15, dur:'5 min', tags:['night'] },
{ id:'mn28', coach:'mental', title:'Spend 10 minutes alone', advice:'Comfort with yourself is a form of freedom.', xp:15, dur:'10 min', tags:['evening'] },
{ id:'mn29', coach:'mental', title:'Replace one complaint with gratitude', advice:'The mind finds what it is trained to look for.', xp:15, dur:'5 min', tags:['anytime'] },
{ id:'mn30', coach:'mental', title:'Visualize your ideal day', advice:'Mental rehearsal often precedes real achievement.', xp:20, dur:'10 min', tags:['morning'] },
{ id:'mn31', coach:'mental', title:'Observe your self-talk', advice:'Speak to yourself like someone you care about.', xp:15, dur:'5 min', tags:['anytime'] },
{ id:'mn32', coach:'mental', title:'Practice saying no', advice:'Every meaningful yes requires a thoughtful no.', xp:20, dur:'5 min', tags:['social'] },
{ id:'mn33', coach:'mental', title:'Write down what is bothering you', advice:'Problems become clearer when removed from your head.', xp:15, dur:'5 min', tags:['night'] },
{ id:'mn34', coach:'mental', title:'Focus on one thing only', advice:'Multitasking divides attention. Focus multiplies it.', xp:20, dur:'20 min', tags:['office'] },
{ id:'mn35', coach:'mental', title:'Reflect on a recent success', advice:'Confidence is built from remembered victories.', xp:15, dur:'5 min', tags:['night'] },
{ id:'mn36', coach:'mental', title:'Do a body awareness check', advice:'Your body often notices stress before your mind does.', xp:10, dur:'3 min', tags:['anytime'] },
{ id:'mn37', coach:'mental', title:'Reconnect with a happy memory', advice:'Your mind contains evidence of joy. Revisit it.', xp:15, dur:'5 min', tags:['evening'] },
{ id:'mn38', coach:'mental', title:'Spend time without consuming content', advice:'Not every moment needs to be filled.', xp:20, dur:'15 min', tags:['anytime'] },
{ id:'mn39', coach:'mental', title:'Write one thing you learned about yourself', advice:'Self-awareness is a lifelong advantage.', xp:20, dur:'10 min', tags:['night'] },
{ id:'mn40', coach:'mental', title:'Celebrate a small victory', advice:'Big achievements are built from small wins.', xp:15, dur:'5 min', tags:['anytime'] },

{ id:'sk1', coach:'skill', title:'Practice active listening today',    advice:'Listen to understand, not to reply. It changes everything.',                               xp:15, dur:'—',      tags:['anytime','office'] },
{ id:'sk2', coach:'skill', title:'Write a clear, structured email',    advice:'Clear writing is clear thinking. Practice it daily.',                                      xp:15, dur:'10 min', tags:['office','morning'] },
{ id:'sk3', coach:'skill', title:'Give someone genuine feedback',      advice:'Honest, kind feedback is one of the rarest gifts.',                                        xp:20, dur:'10 min', tags:['office','afternoon'] },
{ id:'sk4', coach:'skill', title:'Practice saying no gracefully',      advice:'Saying no to the wrong things is saying yes to the right ones.',                          xp:20, dur:'—',      tags:['anytime'] },
{ id:'sk5', coach:'skill', title:'Present an idea clearly to someone', advice:'If you can\'t explain it simply, you don\'t understand it yet.',                          xp:20, dur:'10 min', tags:['office','afternoon'] },
{ id:'sk6', coach:'skill', title:'Read about emotional intelligence',  advice:'EQ is the skill that multiplies all others.',                                              xp:20, dur:'15 min', tags:['evening','office'] },
{ id:'sk7', coach:'skill', title:'Work on time management today',      advice:'You have 24 hours. Spend them or invest them — your choice.',                             xp:15, dur:'—',      tags:['morning','office'] },
{ id:'sk8', coach:'skill', title:'Practice conflict resolution skills',advice:'Conflicts resolved well build stronger relationships.',                                    xp:20, dur:'10 min', tags:['office'] },
{ id:'sk9', coach:'skill', title:'Observe your communication patterns',advice:'Self-awareness in communication is the beginning of mastery.',                            xp:15, dur:'—',      tags:['anytime'] },
{ id:'sk10', coach:'skill', title:'Learn about negotiation basics', advice:'Every day is a negotiation. Learn to navigate it well.', xp:20, dur:'15 min', tags:['office', 'evening'] },
{ id:'sk11', coach:'skill', title:'Summarize a complex topic in 3 sentences', advice:'True understanding appears when complexity becomes simplicity.', xp:20, dur:'10 min', tags:['office'] },
{ id:'sk12', coach:'skill', title:'Ask better questions today', advice:'The quality of your questions determines the quality of your answers.', xp:15, dur:'—', tags:['anytime'] },
{ id:'sk13', coach:'skill', title:'Practice making eye contact', advice:'Confidence is often communicated before words are spoken.', xp:10, dur:'5 min', tags:['social'] },
{ id:'sk14', coach:'skill', title:'Observe a skilled communicator', advice:'Mastery leaves clues for those who pay attention.', xp:15, dur:'10 min', tags:['office'] },
{ id:'sk15', coach:'skill', title:'Speak slower during conversations', advice:'People trust clarity more than speed.', xp:15, dur:'—', tags:['social'] },
{ id:'sk16', coach:'skill', title:'Practice decision making', advice:'Small decisions train you for bigger ones.', xp:20, dur:'10 min', tags:['office'] },
{ id:'sk17', coach:'skill', title:'Learn a memory technique', advice:'A stronger memory reduces dependence on reminders.', xp:20, dur:'15 min', tags:['anytime'] },
{ id:'sk18', coach:'skill', title:'Practice reading body language', advice:'What people do often matters more than what they say.', xp:15, dur:'10 min', tags:['social'] },
{ id:'sk19', coach:'skill', title:'Explain a concept to a beginner', advice:'Teaching exposes gaps that learning hides.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk20', coach:'skill', title:'Improve one daily workflow', advice:'Small efficiency gains compound for years.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk21', coach:'skill', title:'Practice storytelling', advice:'Facts inform. Stories persuade and inspire.', xp:20, dur:'15 min', tags:['social'] },
{ id:'sk22', coach:'skill', title:'Handle a difficult conversation calmly', advice:'Character is revealed when emotions are tested.', xp:25, dur:'15 min', tags:['social'] },
{ id:'sk23', coach:'skill', title:'Practice persuasive speaking', advice:'Influence comes from clarity, trust, and empathy.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk24', coach:'skill', title:'Improve your note-taking system', advice:'Your future self will thank you for organized thinking.', xp:15, dur:'15 min', tags:['office'] },
{ id:'sk25', coach:'skill', title:'Practice critical thinking', advice:'Question assumptions before accepting conclusions.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk26', coach:'skill', title:'Identify one cognitive bias', advice:'The mind makes shortcuts. Awareness prevents mistakes.', xp:20, dur:'10 min', tags:['anytime'] },
{ id:'sk27', coach:'skill', title:'Practice empathy intentionally', advice:'Understanding others is a competitive advantage in life.', xp:20, dur:'10 min', tags:['social'] },
{ id:'sk28', coach:'skill', title:'Give a genuine compliment', advice:'Recognition strengthens relationships and trust.', xp:10, dur:'2 min', tags:['social'] },
{ id:'sk29', coach:'skill', title:'Practice staying silent', advice:'Sometimes the strongest communication is listening.', xp:15, dur:'5 min', tags:['social'] },
{ id:'sk30', coach:'skill', title:'Learn one productivity technique', advice:'Systems outperform motivation in the long run.', xp:15, dur:'10 min', tags:['office'] },
{ id:'sk31', coach:'skill', title:'Break a problem into smaller parts', advice:'Complexity becomes manageable when divided.', xp:20, dur:'10 min', tags:['office'] },
{ id:'sk32', coach:'skill', title:'Practice prioritization', advice:'Doing the right thing matters more than doing many things.', xp:20, dur:'10 min', tags:['office'] },
{ id:'sk33', coach:'skill', title:'Learn one presentation technique', advice:'Great ideas deserve great delivery.', xp:15, dur:'10 min', tags:['office'] },
{ id:'sk34', coach:'skill', title:'Observe your emotional triggers', advice:'Self-control begins with self-awareness.', xp:20, dur:'10 min', tags:['anytime'] },
{ id:'sk35', coach:'skill', title:'Practice patience intentionally', advice:'Patience turns reaction into response.', xp:15, dur:'—', tags:['anytime'] },
{ id:'sk36', coach:'skill', title:'Write a concise message', advice:'Brevity is respect for other people\'s time.', xp:15, dur:'5 min', tags:['office'] },
{ id:'sk37', coach:'skill', title:'Learn one persuasion principle', advice:'Understanding influence helps in every career.', xp:20, dur:'10 min', tags:['office'] },
{ id:'sk38', coach:'skill', title:'Practice focus for 25 minutes', advice:'Attention is the currency of achievement.', xp:20, dur:'25 min', tags:['office'] },
{ id:'sk39', coach:'skill', title:'Turn feedback into action', advice:'Feedback creates value only when applied.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk40', coach:'skill', title:'Practice confident posture', advice:'How you carry yourself affects how you feel and are perceived.', xp:10, dur:'5 min', tags:['anytime'] },
{ id:'sk41', coach:'skill', title:'Improve one recurring task', advice:'Repeated work deserves repeated improvement.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk42', coach:'skill', title:'Practice structured thinking', advice:'Clear structure makes complex ideas easier to communicate.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk43', coach:'skill', title:'Learn one leadership lesson', advice:'Leadership starts long before a leadership title.', xp:20, dur:'10 min', tags:['office'] },
{ id:'sk44', coach:'skill', title:'Practice staying calm under pressure', advice:'Anyone can perform when things are easy.', xp:25, dur:'10 min', tags:['office'] },
{ id:'sk45', coach:'skill', title:'Review a recent mistake', advice:'Mistakes become assets when lessons are extracted.', xp:20, dur:'10 min', tags:['night'] },
{ id:'sk46', coach:'skill', title:'Practice adaptability', advice:'The future belongs to fast learners and fast adapters.', xp:20, dur:'—', tags:['anytime'] },
{ id:'sk47', coach:'skill', title:'Learn one networking skill', advice:'Opportunities often travel through people.', xp:15, dur:'10 min', tags:['social'] },
{ id:'sk48', coach:'skill', title:'Practice handling objections', advice:'Resistance is part of communication, not a failure of it.', xp:20, dur:'15 min', tags:['office'] },
{ id:'sk49', coach:'skill', title:'Identify one area to improve', advice:'Growth begins with honest self-assessment.', xp:15, dur:'10 min', tags:['night'] },
{ id:'sk50', coach:'skill', title:'Apply one thing you learned recently', advice:'Knowledge becomes skill only through action.', xp:25, dur:'15 min', tags:['anytime'] },

{ id:'b1',  coach:'biz', title:'Read a business case study',          advice:'Other people\'s business lessons cost you nothing. Learn them.',                           xp:25, dur:'20 min', tags:['office','evening'] },
{ id:'b2',  coach:'biz', title:'Study a marketing concept',           advice:'Marketing is how ideas spread. Understanding it gives you leverage.',                      xp:20, dur:'15 min', tags:['office','afternoon'] },
{ id:'b3',  coach:'biz', title:'Analyze a successful product',        advice:'Successful products solve real problems. Study them to sharpen your eye.',                 xp:20, dur:'15 min', tags:['office'] },
{ id:'b4',  coach:'biz', title:'Learn about SaaS business models',    advice:'Software is eating the world. Know the business behind it.',                               xp:25, dur:'20 min', tags:['office','evening'] },
{ id:'b5',  coach:'biz', title:'Study financial statements basics',   advice:'Entrepreneurs who understand numbers build businesses that last.',                          xp:25, dur:'20 min', tags:['office','evening'] },
{ id:'b6',  coach:'biz', title:'Research a startup that interests you',advice:'Every great company started with an obsessed founder who studied the problem.',           xp:20, dur:'20 min', tags:['office','evening'] },
{ id:'b7',  coach:'biz', title:'Learn about product-market fit',      advice:'PMF is why 90% of startups fail without it. Understand it deeply.',                       xp:25, dur:'15 min', tags:['office','afternoon'] },
{ id:'b8',  coach:'biz', title:'Study customer acquisition strategies',advice:'Growth without a system is luck. Learn the levers.',                                      xp:20, dur:'15 min', tags:['office'] },
{ id:'b9',  coach:'biz', title:'Read about pricing strategy',         advice:'Pricing is the most powerful lever in business. Know it.',                                 xp:20, dur:'15 min', tags:['office','evening'] },
{ id:'b10', coach:'biz', title:'Write down a business idea', advice:'Ideas kept in your head die. Write them down. Let them breathe.', xp:15, dur:'10 min', tags:['evening','night'] },
{ id:'b11', coach:'biz', title:'Identify a problem worth solving', advice:'Great businesses start with painful problems, not clever solutions.', xp:25, dur:'15 min', tags:['office','evening'] },
{ id:'b12', coach:'biz', title:'Validate a business idea', advice:'Evidence beats excitement. Validate before you build.', xp:30, dur:'20 min', tags:['office'] },
{ id:'b13', coach:'biz', title:'Talk to a potential customer', advice:'Customers reveal truths that assumptions never will.', xp:30, dur:'20 min', tags:['office'] },
{ id:'b14', coach:'biz', title:'Study a competitor', advice:'Competitors teach you what works and what is missing.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b15', coach:'biz', title:'Learn about customer retention', advice:'Keeping customers is often more profitable than finding new ones.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b16', coach:'biz', title:'Calculate customer lifetime value', advice:'Smart businesses think beyond the first sale.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b17', coach:'biz', title:'Study a failed startup', advice:'Failure leaves lessons for those willing to learn them.', xp:25, dur:'20 min', tags:['evening'] },
{ id:'b18', coach:'biz', title:'Learn about recurring revenue', advice:'Predictable revenue creates predictable growth.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b19', coach:'biz', title:'Research a profitable niche', advice:'Riches are often hidden inside focused markets.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b20', coach:'biz', title:'Write a one-page business plan', advice:'A simple plan executed beats a perfect plan ignored.', xp:30, dur:'30 min', tags:['office','evening'] },
{ id:'b21', coach:'biz', title:'Study sales fundamentals', advice:'Every business survives because somebody sold something.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b22', coach:'biz', title:'Analyze a company\'s revenue model', advice:'Follow the money and you will understand the business.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b23', coach:'biz', title:'Learn about business moats', advice:'The strongest businesses are difficult to copy.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b24', coach:'biz', title:'Review a landing page', advice:'Every element should move visitors closer to action.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b25', coach:'biz', title:'Study consumer psychology', advice:'People buy emotionally and justify logically.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b26', coach:'biz', title:'Learn about conversion funnels', advice:'Growth becomes predictable when the funnel is understood.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b27', coach:'biz', title:'Calculate a product\'s profit margin', advice:'Revenue is vanity. Profit is reality.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b28', coach:'biz', title:'Read a founder story', advice:'Every successful founder once faced the same uncertainty you do.', xp:20, dur:'15 min', tags:['evening'] },
{ id:'b29', coach:'biz', title:'Learn about unit economics', advice:'Healthy businesses are built on healthy numbers.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b30', coach:'biz', title:'Define a target customer persona', advice:'When you try to serve everyone, you serve no one.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b31', coach:'biz', title:'Research an emerging market', advice:'Opportunities often appear where attention is still scarce.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b32', coach:'biz', title:'Study a subscription business', advice:'Recurring customers create compounding value.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b33', coach:'biz', title:'List 10 business ideas', advice:'Quantity creates quality. Great ideas emerge from many attempts.', xp:20, dur:'15 min', tags:['evening'] },
{ id:'b34', coach:'biz', title:'Analyze why people buy', advice:'Understanding demand is more valuable than creating supply.', xp:25, dur:'15 min', tags:['office'] },
{ id:'b35', coach:'biz', title:'Learn about negotiation', advice:'Business rewards those who create win-win outcomes.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b36', coach:'biz', title:'Study brand positioning', advice:'A strong position makes competition less relevant.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b37', coach:'biz', title:'Identify a market gap', advice:'Businesses thrive where customer needs remain unmet.', xp:30, dur:'20 min', tags:['office'] },
{ id:'b38', coach:'biz', title:'Evaluate a side hustle idea', advice:'A small experiment can become a significant opportunity.', xp:25, dur:'20 min', tags:['evening'] },
{ id:'b39', coach:'biz', title:'Study marketplace businesses', advice:'Platforms win by creating value for multiple sides.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b40', coach:'biz', title:'Write a value proposition', advice:'If customers don\'t understand the value, they won\'t buy.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b41', coach:'biz', title:'Learn about customer churn', advice:'Leaky buckets never stay full. Fix retention first.', xp:25, dur:'15 min', tags:['office'] },
{ id:'b42', coach:'biz', title:'Analyze a successful acquisition', advice:'Growth strategies reveal how great companies think.', xp:20, dur:'20 min', tags:['office'] },
{ id:'b43', coach:'biz', title:'Study pricing psychology', advice:'Price influences perception as much as profit.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b44', coach:'biz', title:'Research a local business', advice:'Business lessons exist closer than most people realize.', xp:15, dur:'15 min', tags:['anytime'] },
{ id:'b45', coach:'biz', title:'Learn about cash flow', advice:'Profitable businesses fail when cash runs out.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b46', coach:'biz', title:'Review a startup pitch deck', advice:'Fundraising is storytelling backed by numbers.', xp:20, dur:'15 min', tags:['office'] },
{ id:'b47', coach:'biz', title:'Study the 80/20 principle', advice:'A few actions often drive most results.', xp:15, dur:'10 min', tags:['office'] },
{ id:'b48', coach:'biz', title:'Map a customer journey', advice:'Every purchase follows a sequence of decisions.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b49', coach:'biz', title:'Calculate break-even point', advice:'Know exactly when a business starts creating value.', xp:25, dur:'20 min', tags:['office'] },
{ id:'b50', coach:'biz', title:'Review your best business idea', advice:'Ideas improve when challenged, not when protected.', xp:20, dur:'15 min', tags:['night'] },

{ id:'fu1', coach:'future', title:'Write your 5-year vision',         advice:'Where you want to be in 5 years starts with a clear picture today.',                       xp:30, dur:'20 min', tags:['evening','night'] },
{ id:'fu2', coach:'future', title:'Review your personal mission',     advice:'A mission statement is your north star. Revisit and refine it.',                           xp:20, dur:'10 min', tags:['morning','evening'] },
{ id:'fu3', coach:'future', title:'Build one new positive habit',     advice:'Habits are the compound interest of self-improvement.',                                     xp:25, dur:'—',      tags:['morning','anytime'] },
{ id:'fu4', coach:'future', title:'Eliminate one time-wasting habit', advice:'What you stop doing matters as much as what you start doing.',                             xp:20, dur:'—',      tags:['anytime'] },
{ id:'fu5', coach:'future', title:'Write a letter to your future self',advice:'What would the version of you 5 years from now say? Write back.',                         xp:25, dur:'15 min', tags:['night','evening'] },
{ id:'fu6', coach:'future', title:'Identify your top 3 priorities',   advice:'If everything is priority, nothing is. Choose your three.',                                xp:20, dur:'10 min', tags:['morning'] },
{ id:'fu7', coach:'future', title:'Learn about a role model\'s story',advice:'Standing on the shoulders of giants gives you a head start.',                              xp:20, dur:'15 min', tags:['evening'] },
{ id:'fu8', coach:'future', title:'Reflect on this week\'s growth',   advice:'Growth unseen is growth wasted. Reflect to accelerate.',                                  xp:25, dur:'10 min', tags:['night','evening'] },
{ id:'fu9', coach:'future', title:'Commit to a 30-day challenge',     advice:'30 days is enough to wire a new identity into your brain.',                                xp:35, dur:'—',      tags:['morning','anytime'] },
{ id:'fu10', coach: 'future', title: 'Audit how you spend your time', advice: 'Your calendar reveals your real priorities. Does it match your goals?', xp: 20, dur: '15 min', tags: ['evening', 'office'] },

{ id:'t1', coach:'tech', title:'Read one tech article', advice:'Stay curious. Technology rewards those who keep learning.', xp:15, dur:'15 min', tags:['morning','office'] },
{ id:'t2', coach:'tech', title:'Solve one coding problem', advice:'Every solved problem sharpens your engineering instincts.', xp:25, dur:'30 min', tags:['office'] },
{ id:'t3', coach:'tech', title:'Review a piece of code', advice:'Reading code is often more valuable than writing it.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t4', coach:'tech', title:'Learn a new keyboard shortcut', advice:'Tiny optimizations compound into massive productivity.', xp:10, dur:'5 min', tags:['office'] },
{ id:'t5', coach:'tech', title:'Refactor old code', advice:'Great developers improve code, not just write it.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t6', coach:'tech', title:'Read framework documentation', advice:'The docs know more than tutorials ever will.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t7', coach:'tech', title:'Watch a tech conference talk', advice:'Learn from people building at scale.', xp:25, dur:'30 min', tags:['evening'] },
{ id:'t8', coach:'tech', title:'Learn a Git command', advice:'Version control mastery saves countless hours.', xp:15, dur:'10 min', tags:['office'] },
{ id:'t9', coach:'tech', title:'Explore an open-source project', advice:'The best developers learn from real-world codebases.', xp:25, dur:'30 min', tags:['office'] },
{ id:'t10', coach:'tech', title:'Fix one small bug', advice:'Small victories create strong momentum.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t11', coach:'tech', title:'Read about system design', advice:'Think beyond code. Think systems.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t12', coach:'tech', title:'Optimize a slow query', advice:'Performance is a feature users notice.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t13', coach:'tech', title:'Write a reusable function', advice:'Reusable code is future time saved.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t14', coach:'tech', title:'Study software architecture', advice:'Architecture is where engineering becomes strategy.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t15', coach:'tech', title:'Read one API specification', advice:'APIs are the language of modern software.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t16', coach:'tech', title:'Learn one Linux command', advice:'The terminal is still a superpower.', xp:15, dur:'10 min', tags:['office'] },
{ id:'t17', coach:'tech', title:'Document a process', advice:'Good documentation scales knowledge.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t18', coach:'tech', title:'Review pull requests', advice:'Code reviews grow both reviewer and author.', xp:25, dur:'25 min', tags:['office'] },
{ id:'t19', coach:'tech', title:'Write one automated test', advice:'Confidence grows when testing grows.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t20', coach:'tech', title:'Learn a database concept', advice:'Data is the foundation of software.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t21', coach:'tech', title:'Read about cybersecurity', advice:'Security ignored becomes security regretted.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t22', coach:'tech', title:'Study a design pattern', advice:'Patterns help solve problems elegantly.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t23', coach:'tech', title:'Improve code readability', advice:'Code is read far more than it is written.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t24', coach:'tech', title:'Learn one networking concept', advice:'The internet is magic until you understand it.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t25', coach:'tech', title:'Explore a developer tool', advice:'Tools amplify talent.', xp:15, dur:'15 min', tags:['office'] },
{ id:'t26', coach:'tech', title:'Read release notes', advice:'Stay ahead of changes before they surprise you.', xp:10, dur:'10 min', tags:['office'] },
{ id:'t27', coach:'tech', title:'Debug a difficult issue', advice:'Debugging is where real engineers are forged.', xp:35, dur:'45 min', tags:['office'] },
{ id:'t28', coach:'tech', title:'Watch a coding livestream', advice:'Observe how experts think and work.', xp:20, dur:'30 min', tags:['evening'] },
{ id:'t29', coach:'tech', title:'Learn one AI concept', advice:'AI literacy is becoming a core skill.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t30', coach:'tech', title:'Contribute to open source', advice:'Give back and grow at the same time.', xp:40, dur:'1 hour', tags:['office'] },
{ id:'t31', coach:'tech', title:'Learn Laravel Queues & Jobs', advice:'Synchronous code works. Scalable systems use queues.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t32', coach:'tech', title:'Learn failed jobs handling', advice:'Production systems fail. Great engineers design recovery paths.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t33', coach:'tech', title:'Implement delayed jobs', advice:'Not every task needs to happen now. Timing is architecture.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t34', coach:'tech', title:'Build queue-based notifications', advice:'User experience improves when heavy work moves to the background.', xp:40, dur:'45 min', tags:['office'] },
{ id:'t35', coach:'tech', title:'Learn Events & Listeners', advice:'Loose coupling today prevents technical debt tomorrow.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t36', coach:'tech', title:'Master database transactions', advice:'Data integrity is more important than feature delivery.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t37', coach:'tech', title:'Learn lockForUpdate()', advice:'Concurrency bugs only appear when real users arrive.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t38', coach:'tech', title:'Study race conditions', advice:'Software rarely breaks alone. It breaks when many users act together.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t39', coach:'tech', title:'Practice chunk() queries', advice:'A million records should not scare your application.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t40', coach:'tech', title:'Learn cursor() and lazy()', advice:'Memory efficiency separates production code from demo code.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t41', coach:'tech', title:'Master whereHas()', advice:'Relationships are where Eloquent becomes powerful.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t42', coach:'tech', title:'Practice withCount()', advice:'One optimized query beats a thousand lazy loads.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t43', coach:'tech', title:'Use selectRaw() effectively', advice:'Sometimes abstraction must step aside for performance.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t44', coach:'tech', title:'Write a subquery', advice:'Complex business logic often lives in the database.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t45', coach:'tech', title:'Learn Service Pattern', advice:'Business logic deserves a home beyond controllers.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t46', coach:'tech', title:'Learn Repository Pattern', advice:'Architecture matters when projects survive beyond MVP stage.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t47', coach:'tech', title:'Refactor an old project', advice:'Cleaning old code teaches more than writing new code.', xp:40, dur:'1 hour', tags:['office'] },
{ id:'t48', coach:'tech', title:'Compare Laravel versions', advice:'Framework upgrades are opportunities, not chores.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t49', coach:'tech', title:'Read Laravel release notes', advice:'Framework evolution reveals industry direction.', xp:15, dur:'15 min', tags:['office'] },
{ id:'t50', coach:'tech', title:'Study Laravel internals', advice:'Mastery begins where documentation ends.', xp:40, dur:'45 min', tags:['office'] },
{ id:'t51', coach:'tech', title:'Learn SQL execution plans', advice:'Databases tell you exactly why queries are slow.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t52', coach:'tech', title:'Use EXPLAIN on a query', advice:'Measure before optimizing. Guessing is not engineering.', xp:30, dur:'20 min', tags:['office'] },
{ id:'t53', coach:'tech', title:'Study database indexing', advice:'Indexes are the fastest performance upgrade you can buy.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t54', coach:'tech', title:'Create a composite index', advice:'Understanding access patterns unlocks database speed.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t55', coach:'tech', title:'Learn covering indexes', advice:'The fastest query is the one that avoids touching tables.', xp:30, dur:'25 min', tags:['office'] },
{ id:'t56', coach:'tech', title:'Optimize a JOIN query', advice:'Data relationships should be efficient, not expensive.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t57', coach:'tech', title:'Compare JOIN vs subquery', advice:'Engineering is understanding trade-offs, not memorizing rules.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t58', coach:'tech', title:'Optimize GROUP BY query', advice:'Aggregation is powerful but demands respect.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t59', coach:'tech', title:'Optimize API pagination', advice:'A fast page today prevents outages tomorrow.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t60', coach:'tech', title:'Study database deadlocks', advice:'When systems scale, timing becomes a bug source.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t61', coach:'tech', title:'Install Redis locally', advice:'Every modern backend engineer should know Redis.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t62', coach:'tech', title:'Connect Redis with Laravel', advice:'Speed is often one configuration away.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t63', coach:'tech', title:'Implement caching', advice:'Caching is often cheaper than scaling servers.', xp:30, dur:'25 min', tags:['office'] },
{ id:'t64', coach:'tech', title:'Store sessions in Redis', advice:'State management becomes critical at scale.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t65', coach:'tech', title:'Use Redis queues', advice:'Fast applications delegate heavy work.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t66', coach:'tech', title:'Implement Redis locks', advice:'Distributed systems need distributed protection.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t67', coach:'tech', title:'Build a Redis rate limiter', advice:'Protect your APIs before users abuse them.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t68', coach:'tech', title:'Install Docker', advice:'If it works only on your machine, it does not work.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t69', coach:'tech', title:'Run PHP in Docker', advice:'Consistency beats configuration drift.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t70', coach:'tech', title:'Run MySQL in Docker', advice:'Infrastructure should be reproducible.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t71', coach:'tech', title:'Run Redis in Docker', advice:'Modern development mirrors production.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t72', coach:'tech', title:'Create docker-compose setup', advice:'Automation reduces onboarding friction.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t73', coach:'tech', title:'Containerize a Laravel project', advice:'Packaging software is part of building software.', xp:40, dur:'45 min', tags:['office'] },
{ id:'t74', coach:'tech', title:'Learn caching strategies', advice:'The fastest database query is the one never executed.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t75', coach:'tech', title:'Study API rate limiting', advice:'Every public API eventually needs protection.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t76', coach:'tech', title:'Learn load balancing', advice:'One server is a machine. Multiple servers are a system.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t77', coach:'tech', title:'Understand horizontal scaling', advice:'Scale architecture before scaling hardware.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t78', coach:'tech', title:'Study database replication', advice:'Availability starts with redundancy.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t79', coach:'tech', title:'Compare monolith vs microservices', advice:'Architecture is context, not religion.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t80', coach:'tech', title:'Learn API gateway concepts', advice:'As systems grow, entry points become critical.', xp:30, dur:'25 min', tags:['office'] },
{ id:'t81', coach:'tech', title:'Study queue architecture', advice:'Reliable systems embrace asynchronous thinking.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t82', coach:'tech', title:'Master REST API design', advice:'Good APIs feel obvious. Great APIs feel invisible.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t83', coach:'tech', title:'Design pagination properly', advice:'Every dataset eventually becomes large.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t84', coach:'tech', title:'Build search and filtering APIs', advice:'Users rarely want everything. Help them find something.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t85', coach:'tech', title:'Learn API versioning', advice:'Change is inevitable. Breaking clients is optional.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t86', coach:'tech', title:'Study idempotency', advice:'Reliable APIs survive duplicate requests.', xp:30, dur:'25 min', tags:['office'] },
{ id:'t87', coach:'tech', title:'Design a webhook system', advice:'Events connect systems better than polling.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t88', coach:'tech', title:'Implement JWT authentication', advice:'Authentication is trust expressed in code.', xp:30, dur:'25 min', tags:['office'] },
{ id:'t89', coach:'tech', title:'Improve request validation', advice:'Bad data is easier to prevent than repair.', xp:20, dur:'20 min', tags:['office'] },
{ id:'t90', coach:'tech', title:'Install PHPUnit properly', advice:'Testing starts with removing excuses.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t91', coach:'tech', title:'Write your first unit test', advice:'A small test today prevents a big bug tomorrow.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t92', coach:'tech', title:'Write a feature test', advice:'Test behavior, not implementation.', xp:30, dur:'25 min', tags:['office'] },
{ id:'t93', coach:'tech', title:'Learn mocking techniques', advice:'Isolation helps reveal the truth.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t94', coach:'tech', title:'Practice database testing', advice:'Critical logic deserves verification.', xp:30, dur:'30 min', tags:['office'] },
{ id:'t95', coach:'tech', title:'Add tests to legacy code', advice:'The safest refactor begins with a test.', xp:35, dur:'30 min', tags:['office'] },
{ id:'t96', coach:'tech', title:'Build a debugging workflow with AI', advice:'AI should amplify your thinking, not replace it.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t97', coach:'tech', title:'Practice prompt engineering', advice:'Clear instructions produce clear outcomes.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t98', coach:'tech', title:'Use AI for refactoring', advice:'Let AI handle repetition while you handle judgment.', xp:25, dur:'20 min', tags:['office'] },
{ id:'t99', coach:'tech', title:'Use AI for code reviews', advice:'A second pair of eyes never hurts.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t100', coach:'tech', title:'Build a prompt library', advice:'Reusable knowledge is a productivity multiplier.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t101', coach:'tech', title:'Improve technical writing', advice:'Great engineers communicate as well as they code.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t102', coach:'tech', title:'Write a pull request description', advice:'Context saves reviewers hours.', xp:15, dur:'10 min', tags:['office'] },
{ id:'t103', coach:'tech', title:'Explain an architecture diagram', advice:'Understanding is proven through explanation.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t104', coach:'tech', title:'Write a bug report clearly', advice:'A clear bug report is half the fix.', xp:15, dur:'10 min', tags:['office'] },
{ id:'t105', coach:'tech', title:'Practice spoken technical English', advice:'Career growth often follows communication growth.', xp:20, dur:'15 min', tags:['office'] },
{ id:'t106', coach:'tech', title:'Build an inventory system', advice:'Real-world projects create real-world skills.', xp:50, dur:'2 hours', tags:['office'] },
{ id:'t107', coach:'tech', title:'Build a courier settlement system', advice:'Business complexity is the best teacher.', xp:50, dur:'2 hours', tags:['office'] },
{ id:'t108', coach:'tech', title:'Build an expense tracker API', advice:'Small projects become portfolio assets.', xp:40, dur:'1 hour', tags:['office'] },
{ id:'t109', coach:'tech', title:'Build notification system with queues', advice:'Scalable communication requires asynchronous thinking.', xp:45, dur:'1 hour', tags:['office'] },
{ id:'t110', coach:'tech', title:'Build a Redis rate-limited API', advice:'Production-ready systems defend themselves.', xp:45, dur:'1 hour', tags:['office'] },
{ id:'t111', coach:'tech', title:'Solve one SQL optimization challenge', advice:'Performance skill compounds throughout your career.', xp:25, dur:'20 min', tags:['weekly'] },
{ id:'t112', coach:'tech', title:'Refactor ugly code', advice:'Leave the codebase better than you found it.', xp:25, dur:'20 min', tags:['weekly'] },
{ id:'t113', coach:'tech', title:'Read a backend engineering article', advice:'Borrow lessons from engineers who solved bigger problems.', xp:15, dur:'15 min', tags:['weekly'] },
{ id:'t114', coach:'tech', title:'Build one mini feature', advice:'Progress comes from shipping, not planning.', xp:30, dur:'30 min', tags:['weekly'] },
{ id:'t115', coach:'tech', title:'Document one learning note', advice:'Knowledge written is knowledge retained.', xp:15, dur:'10 min', tags:['weekly'] },
];
